# Install numpy

In [ ]:
!pip install numpy - google collab

In [1]:
import numpy as np

# Array Initialization

In [6]:
# Single Dimension
a = np.array([7,8,9,2])
print(a)

[7 8 9 2]


In [3]:
# Multi Dimension
b = np.array([(7,9,9,2),(16,5,7,3)])
print(b)

[[ 7  9  9  2]
 [16  5  7  3]]


# Generate array

In [7]:
# Range of values
c = np.arange(5)
print(c)

[0 1 2 3 4]


In [9]:
# Set of values by interval
# (start, end, no.of.values.of.equal.interval)
d = np.linspace(1,10,5)
print(d)

[ 1.    3.25  5.5   7.75 10.  ]


In [4]:
print(np.zeros(3))

[0. 0. 0.]


In [5]:
print(np.ones(3))

[1. 1. 1.]


In [44]:
print(np.random.rand(2))

[0.0140631  0.03150684]


In [56]:
print(np.random.randn(2))

[-1.16231455  0.79000145]


In [22]:
print(np.random.randint(0,5,3))

[1 3 0]


# Array Properties

In [20]:
a = np.array(["a","b","c"])
b = np.array([(2.0,3,4),(5,4,6)])

In [21]:
# array dimension
print(a.ndim)  # 1
print(b.ndim)  # 2

1
2


In [22]:
# no. of elements in array
print(a.size) #3
print(b.size) #6

3
6


In [23]:
# byte size of each element
print(a.itemsize)   #4
print(b.itemsize)   #8

4
8


In [24]:
# memory occupied by array
print(a.itemsize*a.size)  #12
print(b.itemsize*b.size)  #48

12
48


In [27]:
# data type of array
print(a.dtype)  #<U1
print(b.dtype)  #float64

<U1
float64


In [29]:
# shape of array (rows & columns)
print(a.shape)  #(3,)
print(b.shape)  #(2,3)

(3,)
(2, 3)


# Array Reshape

In [32]:
a = np.array([(2,3),(3,4),(6,7)])
print(a)
a.shape

[[2 3]
 [3 4]
 [6 7]]


(3, 2)

In [34]:
a = a.reshape(2,3)
print(a)
a.shape

[[2 3 3]
 [4 6 7]]


(2, 3)

# Array Slicing

In [24]:
a = np.array([(1,2,3,4), (5,6,7,8), (3,4,5,6)])

In [40]:
a.shape

(3, 4)

In [25]:
# Select element from certain row and column
print(a[0,2])
print(a[2,3])
print(a[1,3])

3
6
8


In [41]:
print(a[0:,1])
print(a[1:,3])

[2 6 4]
[8 6]


In [26]:
print(a[0])

[1 2 3 4]


In [28]:
print(a[1:])

[[5 6 7 8]
 [3 4 5 6]]


In [43]:
print(a[:2])

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
b = np.array([1,2,3,4])

In [31]:
print(b[0])

1


In [36]:
print(b[:])

[1 2 3 4]


In [37]:
print(b[1:3])

[2 3]


In [38]:
print(b[1:])

[2 3 4]


In [39]:
print(b[:3])

[1 2 3]


# Array Operation

In [55]:
a = np.array([4,8,3])

In [56]:
print(a.min())

3


In [57]:
print(a.max())

8


In [58]:
print(a.sum())

15


In [59]:
print(np.sqrt(a))

[2.         2.82842712 1.73205081]


In [60]:
# Standard deviation
print(np.std(a))

2.160246899469287


In [61]:
# Exponential
print(np.exp(a))

[  54.59815003 2980.95798704   20.08553692]


In [62]:
# natural log - ln
print(np.log(a))

[1.38629436 2.07944154 1.09861229]


In [63]:
# log to base 10
print(np.log10(a))

[0.60205999 0.90308999 0.47712125]


# Array arithmetic operation

In [8]:
a = np.array([(1,2,3), (5,6,7)])
c = np.array([(3,4,5), (2,6,8)])

In [48]:
print(a+c)

[[ 4  6  8]
 [ 7 12 15]]


In [49]:
print(a-c)

[[-2 -2 -2]
 [ 3  0 -1]]


In [50]:
print(a*c)

[[ 3  8 15]
 [10 36 56]]


In [51]:
print(a/c)

[[0.33333333 0.5        0.6       ]
 [2.5        1.         0.875     ]]


In [9]:
# Sum of each element of 1st dim array with same index with another dim element
# [1+5 2+6 3+7]
print(a.sum(axis=0))

[ 6  8 10]


In [69]:
# sum of all element is 1st dim & sum of all element is 2nd dim
print(a.sum(axis=1))

[ 6 18]


In [71]:
# vertical stack - combine arrays vertically
print(np.vstack((a,c)))

[[1 2 3]
 [5 6 7]
 [3 4 5]
 [2 6 8]]


In [72]:
# Horizontal stack - combine arrays horizontally
print(np.hstack((a,c)))

[[1 2 3 3 4 5]
 [5 6 7 2 6 8]]


In [73]:
# combine as single dimension
print(a.ravel())

[1 2 3 5 6 7]
