In [1]:
import numpy as np
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
# One hot encoding each review
from tensorflow.keras.preprocessing.text import one_hot

vocab_size = 30
encoded_reviews = [one_hot(review, vocab_size) for review in reviews]
print(encoded_reviews)

[[1, 21], [20, 23], [10, 17], [18, 29, 15], [9, 8, 5], [4, 21], [16, 8, 11], [7, 21], [7, 16], [19, 2]]


In [3]:
# Padding each vector to bring it in same length
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 1 21  0]
 [20 23  0]
 [10 17  0]
 [18 29 15]
 [ 9  8  5]
 [ 4 21  0]
 [16  8 11]
 [ 7 21  0]
 [ 7 16  0]
 [19  2  0]]


In [4]:
X = padded_reviews
y = sentiment

In [9]:
# Defining our model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X, y, epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.3000 - loss: 0.7015
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.3000 - loss: 0.7002
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.3000 - loss: 0.6989
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.3000 - loss: 0.6976
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3000 - loss: 0.6963
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3000 - loss: 0.6950
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.3000 - loss: 0.6937
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.3000 - loss: 0.6924
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6911
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6873
Epo

In [10]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 3, 4)           │           120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_3 (Flatten)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401 (1.57 KB)

 Trainable params: 133 (532.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 268 (1.05 KB)

In [12]:
# Get embeddings of vectors
weights = model.get_layer('embedding_4').get_weights()[0]
weights

array([[-0.0063885 , -0.03437916, -0.02839362,  0.0185667 ],
       [ 0.01130934,  0.01802355,  0.09360003, -0.02159826],
       [-0.05012379,  0.04732238,  0.07253855,  0.03971541],
       [ 0.0320924 , -0.03225304,  0.007087  ,  0.03762238],
       [-0.0477219 , -0.08313077, -0.06653426, -0.00041527],
       [-0.06494255,  0.04177709, -0.01224776,  0.00687964],
       [ 0.02408398,  0.02982442,  0.00594391,  0.02483651],
       [-0.04248828, -0.11078937, -0.04379126,  0.03883092],
       [-0.03227556,  0.0127801 ,  0.04094305, -0.03768306],
       [ 0.08263207,  0.03639404,  0.06162774, -0.05100838],
       [ 0.0436615 ,  0.09576126,  0.02766347, -0.09586145],
       [ 0.02853435, -0.01551512,  0.00619319, -0.04384957],
       [-0.00609088, -0.01907104, -0.02466575,  0.04359288],
       [ 0.02639334,  0.00355129, -0.0196071 , -0.04442122],
       [ 0.04860188,  0.00408499, -0.02625685, -0.04265286],
       [-0.02706519,  0.01229652, -0.09043995,  0.03617722],
       [-0.10088767,  0.

In [15]:
# Embedding of nice
weights[1]

array([ 0.01130934,  0.01802355,  0.09360003, -0.02159826], dtype=float32)

In [14]:
# Embedding of good
weights[17]

array([ 0.0461241 , -0.08799999, -0.03855571, -0.09387045], dtype=float32)